version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

executors:
  default:
    docker:
      - image: circleci/node:current

commands:
  install-dependencies:
    steps:
      - run: npm ci
  cache-dependencies:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./infrastructure/node_modules
  restore-dependencies:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
  deploy-app:
    steps:
      - run: npm run cdk deploy --all

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - aws-cli/setup
      - deploy-app

workflows:
  version: 2
  ci-master:
    jobs:
      - deploy:
          context: aws-account
          requires:
            - build