version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

executors:
  default:
    docker:
      - image: circleci/node:current

commands:
  install-dependencies:
    steps:
      - run: npm ci
  cache-dependencies:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./infrastructure/node_modules
  restore-dependencies:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
  deploy-app:
    steps:
      - run: npm run deploy
  lint:
    steps:
      - run: npm run lint
  test:
    steps:
      - run: npm run test
  install-newrelic-cli:
    steps:
      - run: pip3 install newrelic-lambda-cli
  install-newrelic-integration:
    steps:
      - run: newrelic-lambda integrations install --nr-account-id $NEWRELIC_ACCOUNT_ID --nr-api-key $NEWRELIC_API_KEY --nr-region $NEWRELIC_REGION
  install-newrelic-layers:
    steps:
      - run: newrelic-lambda layers install -f all --nr-account-id $NEWRELIC_ACCOUNT_ID

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - restore-dependencies
      - install-dependencies
      - install-newrelic-cli
      - cache-dependencies
      - lint
      - test
      - aws-cli/setup
      - deploy-app
      - install-newrelic-integration
      - install-newrelic-layers

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: aws-account-staging
          filters:
            branches:
              only:
                - master
          
      - deploy:
          context: aws-account-production
          filters:
            branches:
              only:
                - production
